SERVICE_NAME=edge-home
VERSION=1.0.0
TAG=${SERVICE_NAME}:${VERSION}
PORT=1024

MYSQL_USERNAME=root
MYSQL_PASSWORD=SuperDuper!
MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_DB_NAME=source_management
LOG_LEVEL=DEBUG
