version: '3.3'
services:
  edge-home:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1018:8000"
    restart: always
    container_name: edge-home
    image: edge-home:1.0
